# Generated by Django 6.0.7 on 2026-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('job_title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=150)),
                ('job_url', models.URLField(blank=True)),
                ('source', models.TextField(max_length=300)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('applied', 'Beworben'), ('interview', 'Gespräch'), ('task', 'Aufgabe'), ('rejected', 'Absage'), ('accepted', 'Zusage')], max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
