# Generated by Django 6.0.7 on 2026-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0002_alter_jobapplication_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('applied', 'Beworben'), ('interview', 'Gespräch'), ('task', 'Aufgabe'), ('rejected', 'Absage'), ('accepted', 'Zusage')], max_length=20),
        ),
    ]
