# Generated by Django 6.0.7 on 2026-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('applied', 'Beworben'), ('interview', 'Gespräch'), ('task', 'Aufgabe'), ('rejected', 'Absage'), ('accepted', 'Zusage')], default='planned', max_length=20),
        ),
    ]
